# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qrqueue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stonks
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'LBTATools'
  pod 'NVActivityIndicatorView'
  pod 'SnapKit'
  pod 'PhoneNumberKit'
  pod 'SwiftDate'
  pod "Haptica"
  pod 'YandexMobileMetrica', '3.11.1'
  pod 'Charts'
  
end
